# Site settings
title: Sunil Sarraf
email: "sunilsarraf14@gmail.com"
description: "Artist Website"
url: "https://sunilsarraf.github.io"
baseurl: "/sunilsarraf.github.io"
facebook_username: "sunil.sarraf.5"
twitter_username: ""
instagram_username: "sunil.sarraf.5"
github_username:  ""
deviantart_username: ""
flickr_username: ""
discus_shortname: ""
whatsappp: "919425056270"
share: true

# Owner/author information
owner:
  name:   sunil sarraf
  avatar: avatar.png
  favicon: favicon.ico
  info: artist official website

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "https://sunilsarraf.github.io/sunilsarraf.github.io/gallery/"  
  # - JOURNAL: "http://localhost:4000/journal/"
  - ABOUT: "https://sunilsarraf.github.io/sunilsarraf.github.io/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
